### ISSUE TITLE
Item Ordering

### ISSUE THREAD

**Issue by leblzhaw** [Opencast-Moodle/moodle-mod_opencast#11]
Hello all,
Its not really an issue more like a feature request.

When creating a SWITCHcast/OpenCast channel on Moodle and uploading videos, it used to be that the videos were displayed sorted alphanumerically by name.

Now they are displayed sorted by date. This means that the lecturers always have to upload the videos one after the other and the display order can no longer be adjusted afterwards.

Can you make it possible to display the videos sorted by name alphanumerically again?

Best regards
Sascha

**Comment by NinaHerrmann** [comment]
Way too late but I am closing this as it was implemented in #35 :slightly_smiling_face:
