### ISSUE TITLE
Activity completion for Opencast videos

### ISSUE THREAD

**Issue by yanus** [Opencast-Moodle/moodle-mod_opencast#16]
At the moment, the only available option for enabling completion tracking is "Students can manually mark the activity as completed".

Would it be possible to add the option "Student must view this activity to complete it" that most other activities offer.

Additionally, it would be amazing to have completion tracking based on the video progress (e.g. show activity as complete when XX % of the video have been watched), but this is probably trickier to implement.

**Comment by bluetom** [comment]
I am going to implement it like it is realized in other activities: It fires (completion done) when the user opens the activity (view.php).
