### ISSUE TITLE
Backup/restore is incompatible with block_opencasts duplicate on import

### ISSUE THREAD

**Issue by justusdieckmann** [Opencast-Moodle/moodle-mod_opencast#34]
When using the duplicate strategy for importing in block_opencast, a new series is created in the course and the videos are duplicated.

The imported opencast activity are on the other hand still referring to the videos of the old series.

This creates big problems when wanting delete videos upon course deletion, since the activities in any new course will not work anymore when the original gets deleted

**Comment by ferishili** [comment]
Potential fix will be introduced soon in https://github.com/Opencast-Moodle/moodle-block_opencast/issues/193
