### ISSUE TITLE
Error message when viewing video (but video works)

### ISSUE THREAD

**Issue by yanus** [Opencast-Moodle/moodle-mod_opencast#52]
When displaying a video, the following error message is shown at the top of the page:
"There is no video source available. Please contact your system administrator."

Despite this, the video is loaded and played back without any issue.

I don't remember seeing the error before, but not sure when it started showing up. All components are up to date:

Moodle 4.4.1+ (Build: 20240712)
mod_opencast v4.4-r1
tool_opencast v4.4-r1
Opencast 16.1.0

**Comment by bluetom** [comment]
I can't reproduce the error. Could you provide us with more details about when the error occurs?

**Comment by yanus** [comment]
It seems like this has already been addressed in #54, so the issue can be closed.
