### ISSUE TITLE
There was a problem fetching the video.

### ISSUE THREAD

**Issue by untungdwiprasetyo** [Opencast-Moodle/moodle-mod_opencast#53]
I am successfully connect Moodle with Opencast, when upload video from Moodle, it's successfully appear on Opencast page.
But when I am using Video (Opencast) activity, i have got error : There was a problem fetching the video. see capture below

![Screenshot 2024-03-27 141406](https://github.com/user-attachments/assets/261a8e50-e8fa-4e7e-95ec-3cb0b71b368e)

When inspect it, there is no error in Console.

**Comment by untungdwiprasetyo** [comment]
![image](https://github.com/user-attachments/assets/394e95ad-13ef-4540-9d67-28607ed5e80b)

hi @mtneug 

Sorry for just replying,
For videos, yes, from Opencast itself can be played without problems.

**Comment by praaks** [comment]
You should probably check the channel setting for the activity. It should be the same, I think, as the channel the videos were published in.

**Comment by mtneug** [comment]
@praaks is probably right. Our default is currently the `api` channel, which is no longer used in newer Opencast versions. Instead you most probably need to use the `engage-player` channel.

I will close this for now. @untungdwiprasetyo feel free to reopen if this does not solve your issue.
